#!/usr/bin/env node
 
const program = require('commander')
const chalk = require('chalk')
const ora = require('ora')
const download = require('download-git-repo')
download('frank-980/vue-cli_sxd', 'sxd-cli', function (err) {
  console.log(err ? 'Error' : 'Success')
})